config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  
  resources :articles do
    resources :comments, only: %i[ create destroy ]
  end

  devise_for :users

  resources :users, only: %i[ show index destroy]
  
  resources :follows, only: %i[ create destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  scope :feed, ->(following) { where user_id: following }

  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :body, presence: true, length: {minimum: 3, maximum: 500}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true, length: {minimum: 3, maximum: 100}
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'


  validates_uniqueness_of :followed, scope: :follower
  validate :following_someone_else

  private

  def following_someone_else
    if follower == followed
      errors.add(:followed, "Can't follow yourself!")
      return false
    else
      return true
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # Following mechanism
  
  # Followed by user
  has_many :follows_to, foreign_key: 'follower_id', class_name: 'Follow', dependent: :destroy
  has_many :following, through: :follows_to, source: :followed

  # Users' followers
  has_many :follows_from, foreign_key: 'followed_id', class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follows_from, source: :follower

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[ user admin ]

  after_initialize do
    if self.new_record?
      self.role ||= :user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :is_user_authorized?, only: %i[ edit update destroy ]

  # GET /articles or /articles.json
  def index
    if(current_user && params[:f] == "following")
      @pagy, @articles = pagy(Article.feed(current_user.following), items: 5)
    else
      @pagy, @articles = pagy(Article.all, items: 5)
    end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end

    def is_user_authorized?
      if current_user != set_article.user
        is_user_admin?
      end
    end

    def is_user_admin?
      unless current_user.admin?
        redirect_to root_path
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_user_authorized?, only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @article = @comment.article
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@article), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def is_user_authorized?
    comment = Comment.find(params[:id])
    if comment.user_id != current_user.id
      is_user_admin?
    end
  end

  def is_user_admin?
    article = Article.find(params[:article_id])
    unless current_user.admin?
      redirect_to article_path(article)
    end
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_user_authorized?, only: :destroy
  
  def create
    @follow = current_user.follows_to.new(followed_id: params[:follow][:followed_id])
    if @follow.save
      flash[:notice] = "Followed user"
      redirect_to user_path(@follow.followed_id)
    else
      flash[:error] = "Couldn't follow user"
      redirect_to user_path(@follow.followed_id)
    end
  end

  def destroy
    @follow = current_user.follows_to.find_by(followed_id: params[:id])
    @follow.destroy
    flash[:notice] = "Unfollowed user"
    redirect_to user_path(@follow.followed_id)
  end

  private

  def is_user_authorized?
    follow = Follow.find_by(followed_id: params[:id])
    if current_user.id != follow.follower_id
      redirect_to user_path(follow.follower_id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_user_admin?, only: [:index, :destroy]
  
  def show
    @user = User.find(params[:id])
    @articles = Article.all.where(user_id: params[:id])
  end

  def index
    @users = User.all.group(:id, :email).order(:id).
    select(:id, :email).left_joins(:articles, :comments).
    select("COUNT(distinct articles.id) AS article_count, 
            COUNT(distinct comments.id) AS comment_count")
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def is_user_admin?
    if current_user && current_user.admin?
      return true
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
    <div class="modal" id="modal<%= article.id %>">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title"><%= article.title %></h3>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>
                        <%= article.body %>
                    </p>
                </div>
                <div class="modal-footer">
                    <b><%= User.find(article.user_id).email%></b><br>
                    <%= link_to 'Show', article, class: 'btn border py-0 px-1' %>
                    <% if current_user %>
                        <% if current_user == article.user %>
                            <%= link_to 'Edit', edit_article_path(article), class: 'btn border py-0 px-1' %>
                        <% end %>
                        <% if current_user == article.user || current_user.admin? %>
                            <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn border py-0 px-1' %></td>
                        <% end %>
                    <% end %>    
                </div>
            </div>
        </div>
    </div>

    <ul class="list-group">
        <li class="list-group-item active text-white rounded-top pt-2 pb-1 px-2">
            <h3><%= article.title %></h3>
        </li>
        <li class="list-group-item mb-3 rounded-bottom">
            <b><%= link_to User.find(article.user_id).email, User.find(article.user_id), 
                                                        class: "text-decoration-none text-reset" %></b><br>
            <p>
            <% if article.body.split.size() > 50 %>
                <%= article.body.truncate(250, separator: ' ') %>
                <a class="text-decoration-none" data-bs-toggle="modal" href="#modal<%= article.id %>" aria-expanded="false" aria-control="collapse<%= article.id %>">
                read more
                </a>
            <% else %>
                <%= article.body %>
            <% end %>
            </p>
            <%= link_to 'Show', article, class: 'btn border py-0 px-1' %>
            <% if current_user %>
                <% if current_user == article.user %>
                    <%= link_to 'Edit', edit_article_path(article), class: 'btn border py-0 px-1' %>
                <% end %>
                <% if current_user == article.user || current_user.admin? %>
                    <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn border py-0 px-1' %></td>
                <% end %>
            <% end %>
        </li>
    </ul>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control mb-3' %>
  </div>

  <div class="field">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control mb-3'%>
  </div>

  <div class="actions">
    <%= form.submit 'Create Article', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container col-md-6 mt-3 mt-md-4">
    <h1>Editing Article</h1>

    <%= render 'form', article: @article %>
    <%= link_to 'Show', @article, class: 'btn border py-0 px-1 mt-1' %>
    <%= link_to 'Back', articles_path, class: 'btn border py-0 px-1 mt-1' %>
</div>

app/views/articles/index.html.erb
<div class="container-xl col-12 col-sm-6">
  <div class="row justify-content-between mt-5 mb-3">
      <div class="col-6 my-auto">
        <h1>Articles</h1>
      </div>
      <div class="col-6 my-auto">
        <%= link_to 'New Article', new_article_path, class: 'btn btn-primary shadow float-end' %>
      </div>
  </div>
  <%== pagy_bootstrap_nav(@pagy) %>
  <%= render 'articles/article' %>
  <% unless @articles.empty? %>
    <%== pagy_bootstrap_nav(@pagy) %>
  <% end %>
  <br>
</div>

app/views/articles/new.html.erb
<div class="container col-md-6 mt-3 mt-md-4">
    <h1>New Article</h1>

    <%= render 'form', article: @article %>
</div>

app/views/articles/show.html.erb
<div class="container rounded col-11 col-sm-6 mt-3 py-1 border">
  <div class="container rounded bg-white my-3">
    <h1><%= @article.title %></h1>

    <p><%= @article.body %></p>

    <b><%= link_to User.find(@article.user_id).email, User.find(@article.user_id), 
                                        class: "text-decoration-none text-reset" %></b><br>    
    <% if current_user %>
      <% if current_user == @article.user %>
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn border py-0 px-1' %>
      <% end %>
      <% if current_user == @article.user || current_user.admin? %>
        <%= link_to 'Delete', article_path(@article), class: 'btn border py-0 px-1', 
                                                    data: { confirm: "Are you sure?" }, method: :delete %>
      <% end %>
    <% end %>
    
    <%= link_to 'Back', articles_path, class: 'btn border py-0 px-1' %>    
  </div>
  
  <hr>
  
  

    <div class="container rounded bg-white my-3 col">
      <p>Comments:</p>
      <%= render @article.comments %><br>
      <% if current_user %>
        <%= render "comments/form" %>
      <% end %>
    </div>
</div>

app/views/comments/_comment.html.erb
<div class="container rounded col-8 mx-0 p-0">
    <b><%= link_to User.find(comment.user_id).email, User.find(comment.user_id), 
                                        class: "text-decoration-none text-reset" %></b><br>
    <div class="container rounded">
        <%= comment.body %>
    </div>
    <br>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @article.comments.build] do |f| %>
    <div>
        <%= f.text_area :body, class: 'mb-3 form-control' %>
    </div>

    <div> 
        <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/follows/_form.html.erb
<%= form_with model: user.follows_to.build do |f| %>
    <div>
        <%= f.hidden_field :followed_id, value: user.id %>
        <%#= hidden_field_tag :followed_id, user.id %>
    </div>

    <div> 
        <%= f.submit 'Follow', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/layouts/_alerts.html.erb
<div class="notice alert-info" role="alert"><%= notice %></div>
<div class="alert-warning" role="alert"><%= alert %></div>

app/views/layouts/_links.html.erb
<% if current_user %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow">
  <div class="container-fluid">
    <%= link_to "Article site", root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user %>
          <% if params[:f] != "following" %>
            <%= link_to "Following", root_path( f: "following" ), class: 'nav-link' %>
          <% else %>
            <%= link_to "Articles", root_path, class: 'nav-link' %>
          <% end %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Users", users_path, class: 'nav-link' %>
            </li>
          <% end %>
            <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %> 
            <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails social app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<div class="mt-3">
    <div class="card">
        <div class="card-header"><%= user.email %></div>
        <div class="card-body px-4">
            <table class="table table-bordered">
                <tbody>
                    <tr class="row">
                        <td class="col">
                            Articles: 
                        </td>
                        <td class="col">
                            <%= user.article_count %>
                        </td>
                    </tr>
                    <tr class="row">
                        <td class="col">
                            Comments:
                        </td>
                        <td class="col">
                            <%= user.comment_count %>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <%= link_to "Profile", user_path(user), class: "btn border bg-white" %>    
            <% if current_user.admin? %>
                <%= link_to "Delete", user, class: "btn border bg-white", method: :delete %>
            <% end %>
        </div>
    </div>
</div>
<br>

app/views/users/index.html.erb
<div class="container col-11 col-sm-6">
    <%= render @users %>
</div>

app/views/users/show.html.erb
<div class="container col-11 col-sm-6">
    <h1><%= @user.email %></h1>
    <% if current_user && current_user != @user %>
        <div class="mb-1">
        <% if current_user.follows_to.find_by(followed_id: @user.id) %>
            <%= link_to "Unfollow", follow_path(@user), class: 'btn btn-primary', method: :delete%>
            <%#= link_to "Follow user", follows_path,  method: :post, params[followed_id: @user.id] %>
        <% else %>
            <%= render "follows/form", user: @user %>
        <% end %>
        </div>
    <% end %>
    <%= render 'articles/article' %>
</div>